# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DiagnosisWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
import os
import pandas as pd
from PyQt5 import QtCore, QtGui, QtWidgets

# from src.Ui_MainWindow import Ui_MainWindow
# from src.ViewRecordsWindow import ViewRecordsWindow
from src.BloodVesselsExtract import BloodVesselsExtract
from src.Classifier import Classifier
from src.HemorrhageDetection import HemorrhageDetection
from src.ImageProcessing import ImageProcessing
from src.MaExtract import MaExtract
from src.ViewRecordsWindow import ViewRecordsWindow


class DiagnosisWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(976, 587)
        Form.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_5.addWidget(self.line_2, 1, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line = QtWidgets.QFrame(self.frame_4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 2)
        self.gridLayout_5.addWidget(self.frame_4, 0, 0, 1, 3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnExit = QtWidgets.QPushButton(self.frame_2)
        # button clicked
        self.btnExit.clicked.connect(self.btnExit_clicked)
        self.btnExit.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        self.gridLayout_2.addWidget(self.btnExit, 3, 0, 1, 1)
        self.btnDiagnosis = QtWidgets.QPushButton(self.frame_2)
        self.btnDiagnosis.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnDiagnosis.setFont(font)
        self.btnDiagnosis.setObjectName("btnDiagnosis")
        self.gridLayout_2.addWidget(self.btnDiagnosis, 1, 0, 1, 1)
        self.btnDashboard = QtWidgets.QPushButton(self.frame_2)
        # btn action
        self.btnDashboard.clicked.connect(self.openDashboard)
        self.btnDashboard.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setObjectName("btnDashboard")
        self.gridLayout_2.addWidget(self.btnDashboard, 0, 0, 1, 1)
        self.btnViewRecs = QtWidgets.QPushButton(self.frame_2)
        # btn action
        self.btnViewRecs.clicked.connect(self.openViewRecordsWindow)
        self.btnViewRecs.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnViewRecs.setFont(font)
        self.btnViewRecs.setObjectName("btnViewRecs")
        self.gridLayout_2.addWidget(self.btnViewRecs, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(750, 400))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.txtName = QtWidgets.QLineEdit(self.frame_5)
        self.txtName.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.txtName.setFont(font)
        self.txtName.setObjectName("txtName")
        self.horizontalLayout_2.addWidget(self.txtName)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.frame_5)
        self.comboBox.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.txtAge = QtWidgets.QLineEdit(self.frame_5)
        self.txtAge.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.txtAge.setFont(font)
        self.txtAge.setObjectName("txtAge")
        self.horizontalLayout_4.addWidget(self.txtAge)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.txtImage = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtImage.sizePolicy().hasHeightForWidth())
        self.txtImage.setSizePolicy(sizePolicy)
        self.txtImage.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.txtImage.setFont(font)
        self.txtImage.setObjectName("txtImage")
        self.horizontalLayout_5.addWidget(self.txtImage)
        self.txtImage.setReadOnly(True)
        self.btnInputImg = QtWidgets.QPushButton(self.frame_5)
        self.btnInputImg.setObjectName("btnInputImg")
        self.horizontalLayout_5.addWidget(self.btnInputImg)
        # btn action
        self.btnInputImg.clicked.connect(self.btnInputImg_clicked)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.txtPatId = QtWidgets.QLineEdit(self.frame_5)
        self.txtPatId.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.txtPatId.setFont(font)
        self.txtPatId.setObjectName("txtPatId")
        self.horizontalLayout.addWidget(self.txtPatId)
        self.gridLayout_6.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.btnSubmit = QtWidgets.QPushButton(self.frame_5)
        # btn action
        self.btnSubmit.clicked.connect(self.btnSubmit_clicked)
        self.btnSubmit.setMaximumSize(QtCore.QSize(100, 30))
        self.btnDiagnose = QtWidgets.QPushButton(self.frame_5)
        # btn action
        self.btnDiagnose.clicked.connect(self.btnDiagnose_clicked)
        self.btnDiagnose.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnSubmit.setFont(font)
        self.btnSubmit.setObjectName("btnSubmit")
        self.gridLayout_6.addWidget(self.btnSubmit, 6, 0, 1, 1)
        self.btnDiagnose.setFont(font)
        self.btnDiagnose.setObjectName("btnDiagnose")
        self.gridLayout_6.addWidget(self.btnDiagnose, 6, 2, 1, 1)
        self.btnDiagnose.setEnabled(False)
        self.gridLayout_3.addWidget(self.frame_5, 1, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        # self.label_13 = QtWidgets.QLabel(self.frame_6)
        # self.label_13.setObjectName("label_13")
        # self.gridLayout_7.addWidget(self.label_13, 5, 0, 1, 1)
        # self.label_14 = QtWidgets.QLabel(self.frame_6)
        # self.label_14.setObjectName("label_14")
        # self.gridLayout_7.addWidget(self.label_14, 6, 0, 1, 1)
        # self.label_12 = QtWidgets.QLabel(self.frame_6)
        # self.label_12.setObjectName("label_12")
        # self.gridLayout_7.addWidget(self.label_12, 4, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.txtGrade = QtWidgets.QLineEdit(self.frame_6)
        self.txtGrade.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txtGrade.setReadOnly(True)
        self.txtGrade.setObjectName("txtGrade")
        self.horizontalLayout_7.addWidget(self.txtGrade)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.frame_6)

        self.btnReset = QtWidgets.QPushButton(self.frame_6)
        # btn action
        self.btnReset.clicked.connect(self.btnReset_clicked)
        self.btnReset.setMaximumSize(QtCore.QSize(100, 30))
        self.btnReset.setFont(font)
        self.btnReset.setObjectName("btnReset")
        self.gridLayout_7.addWidget(self.btnReset, 6, 0, 1, 1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.txtDr = QtWidgets.QLineEdit(self.frame_6)
        self.txtDr.setReadOnly(True)
        self.txtDr.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txtDr.setObjectName("txtDr")
        self.horizontalLayout_6.addWidget(self.txtDr)
        self.gridLayout_7.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.txtSeverity = QtWidgets.QLineEdit(self.frame_6)
        self.txtSeverity.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txtSeverity.setReadOnly(True)
        self.txtSeverity.setObjectName("txtSeverity")
        self.horizontalLayout_8.addWidget(self.txtSeverity)
        self.gridLayout_7.addLayout(self.horizontalLayout_8, 3, 0, 1, 1)
        # self.label_15 = QtWidgets.QLabel(self.frame_6)
        # self.label_15.setObjectName("label_15")
        # self.gridLayout_7.addWidget(self.label_15, 7, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_6, 1, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.frame_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 0, 1, 2, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.frame_3, 1, 2, 1, 1)
        self.line_2.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Detection of Diabetic Retinopathy and Classification of its Severity"))
        self.label.setText(_translate("Form", "Detection of Diabetic Retinopathy and Classification of its Severity"))
        self.btnExit.setText(_translate("Form", "Exit"))
        self.btnDiagnosis.setText(_translate("Form", "Diagnosis"))
        self.btnDiagnose.setText(_translate("Form", "Diagnose"))
        self.btnDashboard.setText(_translate("Form", "Dashboard"))
        self.btnViewRecs.setText(_translate("Form", "View Previous Records"))
        self.btnReset.setText(_translate("Form", "Reset"))
        self.label_3.setText(_translate("Form", "Diagnosis"))
        self.label_2.setText(_translate("Form", "Name"))
        self.label_5.setText(_translate("Form", "Gender"))
        self.comboBox.setItemText(0, _translate("Form", "Male"))
        self.comboBox.setItemText(1, _translate("Form", "Female"))
        self.comboBox.setItemText(2, _translate("Form", "Others"))
        self.label_6.setText(_translate("Form", "Age"))
        self.label_7.setText(_translate("Form", "Retinal Fundus Image"))
        self.btnInputImg.setText(_translate("Form", "Browse"))
        self.label_4.setText(_translate("Form", "Patient ID"))
        self.btnSubmit.setText(_translate("Form", "Submit"))
        # self.label_13.setText(_translate("Form", "Blood Vessels"))
        # self.label_14.setText(_translate("Form", "Microaneurysms"))
        # self.label_12.setText(_translate("Form", "Preprocessed Image"))
        self.label_9.setText(_translate("Form", "DR Grade"))
        self.label_10.setText(_translate("Form", "Presence of Diabetic Retinopathy"))
        self.label_11.setText(_translate("Form", "Severity"))
        # self.label_15.setText(_translate("Form", "Hemorrhages"))
        self.label_8.setText(_translate("Form", "Results of the Diagnosis"))

    def openDashboard(self):
        self.window = QtWidgets.QMainWindow()
        from src.Ui_MainWindow import Ui_MainWindow
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openViewRecordsWindow(self):
        self.window = QtWidgets.QWidget()
        self.ui = ViewRecordsWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def btnExit_clicked(self):
        QtCore.QCoreApplication.instance().quit()

    def btnInputImg_clicked(self):
        # open file browser to input retinal image file for diagnosis
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.DontUseNativeDialog
        fileName, _ = QtWidgets.QFileDialog.getOpenFileName(
            None,
            "Select Image",
            "",
            "All Files (*);; jpeg Files (*.jpg);; png Files (*.png)",
            options=options)
        if fileName:
            self.txtImage.setText(fileName)
            # self.refreshAll()


    def btnSubmit_clicked(self):
        self.pid = self.txtPatId.text()
        self.name = self.txtName.text()
        self.gender = self.comboBox.currentText()
        self.age = self.txtAge.text()
        self.filePath = self.txtImage.text()
        # print("Patient ID: ", self.pid)
        # print("Name: ", self.name)
        # print("Gender: ", self.gender)
        # print("Age: ", self.age)
        # print(self.filePath)
        if(self.pid != '' and  self.name != '' and self.age != '' and self.filePath != ''):
            # adding data entered to a dataframe and converting the dataframe into a csv file
            df = pd.DataFrame({'Patient_ID': [self.pid], 'Name': [self.name], 'Gender': [self.gender], 'Age': [self.age], 'filepath': [self.filePath]})
            # print(df.head())
            df.to_csv('records.csv')
            self.txtPatId.clear()
            self.txtName.clear()
            self.txtAge.clear()
            self.txtImage.clear()
            self.btnDiagnose.setEnabled(True)
        else:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.setText("Warning")
            msg.setInformativeText("Please fill in all the information.")
            msg.setWindowTitle("Information Required")
            msg.setStandardButtons(QtWidgets.QMessageBox.Ok | QtWidgets.QMessageBox.Cancel)
            # msg.buttonClicked.connect(msgbtn)
            returnValue = msg.exec()
            if returnValue == QtWidgets.QMessageBox.Ok:
                print('OK clicked')
            # print("Please fill in all the information.")

    def btnDiagnose_clicked(self):
        ip = ImageProcessing()
        ip.main()
        bve = BloodVesselsExtract()
        bve.main()
        mex = MaExtract()
        mex.main()
        hd = HemorrhageDetection()
        hd.main()
        cl = Classifier()
        cl.training()

        df = pd.read_csv('records.csv')
        status = df["Diabetic_retinopathy_status"].values[0]
        grade = str(df["Diabetic_retinopathy_grade"].values[0])
        severity = df["Severity"].values[0]
        print(status)
        print(grade)
        print(severity)
        self.txtDr.setText(status)
        self.txtGrade.setText(grade)
        self.txtSeverity.setText(severity)
        os.remove("records.csv")

    def btnReset_clicked(self):
        self.txtDr.clear()
        self.txtGrade.clear()
        self.txtSeverity.clear()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = DiagnosisWindow()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

